version: '3.8'
services:
  db:
    image: postgres:14
    container_name: ${CLIENTE}_${BRANCH}_${CONT_DB}
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_VOLUME=odoo16-main-db-data
    volumes:
      - odoo16-main-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
    ports:
      # <Puerto expuesto> : < Puerto dentro del container>
      # Solo para desarrollo. Comentar en produccion
      - '${POSTGRES_PORT}:5432'
    #expose:
      # Abre el puerto 5432 en el container al exterior sin tocar nada de la configuración del postgresql
      # Solo para desarrollo. Comentar en produccion
      #- '${POSTGRES_PORT}'
    restart: always             # run as a service
    networks:
      red_interna:
        ipv4_address: 192.168.${SUBNET_PAR}.10
  odoo:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    container_name: ${CLIENTE}_${BRANCH}_${CONT_ODOO}
    depends_on:
      - db
    ports:
      - "8016:8069"
      - "8072:8072"
    tty: true
    #command: -- --dev=reload
    # command: odoo scaffold /mnt/extra-addons/test_module
    volumes:
      - odoo16-main-web-data:/var/lib/odoo
      - odoo16-main-opt-data:/opt/odoo
      - ${ODOOCLOUD}/addons:/mnt/extra-addons
      - ${CUSTOMER_PATH}/disc_management:/mnt/disc_management
      - ${ODOOCLOUD}/backups:/opt/odoo/host_backups
      - ${ODOOCLOUD}/config:/etc/odoo
    restart: always             # run as a service
    hostname: ${HOSTNAME}
    networks:
      red_interna:
        ipv4_address: 192.168.${SUBNET_PAR}.20
  pgadmin:
    image: ${PGADMIN_IMAGE_NAME}:${PGADMIN_IMAGE_VERSION}
    container_name: ${CONT_PGADMIN}
    restart: always
    environment:
       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
       PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
       - "${PGADMIN_PORT}:80"
    links:
       - "db:pgsql-server"
    networks:
      red_interna:
        ipv4_address: 192.168.${SUBNET_PAR}.30

secrets:
  postgresql_password:
    file: ${ODOOCLOUD}/odoo_pg_pass

volumes:
  odoo16-main-web-data:
  odoo16-main-db-data:
  odoo16-main-opt-data:

networks:
    red_interna:
        ipam:
            config:
              - subnet: 192.168.${SUBNET_PAR}.0/24